# Generated by Django 5.2.17 on 2026-09-30 16:23

import django.db.models.deletion
import django.utils.timezone
from django.conf import settings
from django.db import migrations, models

from common.db import append_only_trigger


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('sellers', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='SellerAccount',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('balance', models.DecimalField(decimal_places=2, default=0, max_digits=14)),
                ('seller', models.OneToOneField(on_delete=django.db.models.deletion.PROTECT, related_name='account', to='sellers.seller')),
            ],
            options={
                'ordering': ['seller__name', 'id'],
            },
        ),
        migrations.CreateModel(
            name='SellerTransaction',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('kind', models.CharField(choices=[('SALE', 'Sale'), ('PAYOUT', 'Payout'), ('ADJUSTMENT', 'Manual adjustment')], max_length=12)),
                ('amount', models.DecimalField(decimal_places=2, max_digits=14)),
                ('balance_after', models.DecimalField(decimal_places=2, max_digits=14)),
                ('description', models.CharField(blank=True, max_length=255)),
                ('reference', models.CharField(blank=True, help_text='purchase:ID or payout:ID', max_length=100)),
                ('idempotency_key', models.CharField(blank=True, max_length=64)),
                ('created_at', models.DateTimeField(db_index=True, default=django.utils.timezone.now)),
                ('account', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='transactions', to='seller_finance.selleraccount')),
                ('actor', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='+', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-created_at', '-id'],
            },
        ),
        migrations.CreateModel(
            name='SellerPayment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('amount', models.DecimalField(decimal_places=2, max_digits=14)),
                ('status', models.CharField(choices=[('REQUESTED', 'Requested'), ('APPROVED', 'Approved'), ('PROCESSING', 'Processing'), ('PAID', 'Paid'), ('REJECTED', 'Rejected'), ('CANCELLED', 'Cancelled')], default='REQUESTED', max_length=10)),
                ('note', models.CharField(blank=True, max_length=255)),
                ('idempotency_key', models.CharField(blank=True, max_length=64)),
                ('approved_at', models.DateTimeField(blank=True, null=True)),
                ('processed_at', models.DateTimeField(blank=True, null=True)),
                ('paid_at', models.DateTimeField(blank=True, null=True)),
                ('payment_reference', models.CharField(blank=True, help_text='Bank transfer or cash receipt number.', max_length=100)),
                ('rejected_at', models.DateTimeField(blank=True, null=True)),
                ('rejection_reason', models.CharField(blank=True, max_length=255)),
                ('cancelled_at', models.DateTimeField(blank=True, null=True)),
                ('approved_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='+', to=settings.AUTH_USER_MODEL)),
                ('paid_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='+', to=settings.AUTH_USER_MODEL)),
                ('rejected_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='+', to=settings.AUTH_USER_MODEL)),
                ('requested_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.PROTECT, related_name='+', to=settings.AUTH_USER_MODEL)),
                ('seller', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='payouts', to='sellers.seller')),
                ('transaction', models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='+', to='seller_finance.sellertransaction')),
            ],
            options={
                'ordering': ['-created_at', '-id'],
            },
        ),
        migrations.AddConstraint(
            model_name='selleraccount',
            constraint=models.CheckConstraint(condition=models.Q(('balance__gte', 0)), name='seller_account_balance_not_negative'),
        ),
        migrations.AddIndex(
            model_name='sellertransaction',
            index=models.Index(fields=['account', 'created_at'], name='seller_fina_account_8b29fa_idx'),
        ),
        migrations.AddConstraint(
            model_name='sellertransaction',
            constraint=models.CheckConstraint(condition=models.Q(models.Q(('amount__gt', 0), ('kind', 'SALE')), models.Q(('amount__lt', 0), ('kind', 'PAYOUT')), models.Q(('kind', 'ADJUSTMENT'), models.Q(('amount', 0), _negated=True)), _connector='OR'), name='seller_txn_amount_sign_matches_kind'),
        ),
        migrations.AddConstraint(
            model_name='sellertransaction',
            constraint=models.CheckConstraint(condition=models.Q(('balance_after__gte', 0)), name='seller_txn_balance_not_negative'),
        ),
        migrations.AddConstraint(
            model_name='sellertransaction',
            constraint=models.UniqueConstraint(models.F('idempotency_key'), condition=models.Q(('idempotency_key', ''), _negated=True), name='seller_txn_idempotency_key_unique'),
        ),
        migrations.AddConstraint(
            model_name='sellertransaction',
            constraint=models.UniqueConstraint(models.F('reference'), condition=models.Q(('kind__in', ['SALE', 'PAYOUT'])), name='seller_txn_reference_booked_once'),
        ),
        migrations.AddIndex(
            model_name='sellerpayment',
            index=models.Index(fields=['seller', 'status'], name='seller_fina_seller__77d978_idx'),
        ),
        migrations.AddConstraint(
            model_name='sellerpayment',
            constraint=models.CheckConstraint(condition=models.Q(('amount__gt', 0)), name='payout_amount_positive'),
        ),
        migrations.AddConstraint(
            model_name='sellerpayment',
            constraint=models.CheckConstraint(condition=models.Q(models.Q(('status', 'PAID'), _negated=True), models.Q(('transaction__isnull', False), models.Q(('payment_reference', ''), _negated=True)), _connector='OR'), name='payout_paid_is_complete'),
        ),
        migrations.AddConstraint(
            model_name='sellerpayment',
            constraint=models.UniqueConstraint(models.F('idempotency_key'), condition=models.Q(('idempotency_key', ''), _negated=True), name='payout_idempotency_key_unique'),
        ),
        append_only_trigger("seller_finance_sellertransaction"),
    ]
