# Generated by Django 5.2.17 on 2026-09-30 14:50

import apps.goods.models
import django.core.validators
import django.db.models.deletion
import django.utils.timezone
from django.conf import settings
from django.db import migrations, models

from common.db import append_only_trigger


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('sellers', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Good',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('deleted_at', models.DateTimeField(blank=True, db_index=True, null=True)),
                ('name', models.CharField(max_length=255)),
                ('description', models.TextField(blank=True)),
                ('sku', models.CharField(blank=True, help_text="Seller's own product code.", max_length=64)),
                ('price', models.DecimalField(decimal_places=2, max_digits=12, validators=[django.core.validators.MinValueValidator(0)])),
                ('is_active', models.BooleanField(default=True, help_text='Available for sale.')),
                ('track_stock', models.BooleanField(default=True)),
                ('quantity', models.PositiveIntegerField(default=0)),
                ('service_position', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='goods', to='sellers.serviceposition')),
            ],
            options={
                'ordering': ['name', 'id'],
            },
        ),
        migrations.CreateModel(
            name='GoodImage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(upload_to=apps.goods.models._image_path, validators=[django.core.validators.FileExtensionValidator(['jpg', 'jpeg', 'png', 'webp'])])),
                ('alt_text', models.CharField(blank=True, max_length=255)),
                ('position', models.PositiveSmallIntegerField(default=0, help_text='Lowest is shown first.')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('good', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='images', to='goods.good')),
            ],
            options={
                'ordering': ['position', 'id'],
            },
        ),
        migrations.CreateModel(
            name='InventoryMovement',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('kind', models.CharField(choices=[('INITIAL_STOCK', 'Initial stock'), ('RESTOCK', 'Restock'), ('SALE', 'Sale'), ('RETURN', 'Return'), ('DAMAGE', 'Damage / loss'), ('ADJUSTMENT', 'Stock count adjustment')], max_length=15)),
                ('quantity_delta', models.IntegerField()),
                ('quantity_after', models.PositiveIntegerField()),
                ('reason', models.CharField(blank=True, max_length=255)),
                ('reference', models.CharField(blank=True, help_text='e.g. purchase item id for SALE/RETURN.', max_length=100)),
                ('created_at', models.DateTimeField(db_index=True, default=django.utils.timezone.now)),
                ('actor', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='+', to=settings.AUTH_USER_MODEL)),
                ('good', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='movements', to='goods.good')),
            ],
            options={
                'ordering': ['-created_at', '-id'],
            },
        ),
        migrations.AddIndex(
            model_name='good',
            index=models.Index(fields=['service_position', 'is_active'], name='goods_good_service_e4c798_idx'),
        ),
        migrations.AddConstraint(
            model_name='good',
            constraint=models.CheckConstraint(condition=models.Q(('price__gte', 0)), name='good_price_not_negative'),
        ),
        migrations.AddConstraint(
            model_name='good',
            constraint=models.CheckConstraint(condition=models.Q(('quantity__gte', 0)), name='good_quantity_not_negative'),
        ),
        migrations.AddIndex(
            model_name='inventorymovement',
            index=models.Index(fields=['good', 'created_at'], name='goods_inven_good_id_8d6a2c_idx'),
        ),
        migrations.AddConstraint(
            model_name='inventorymovement',
            constraint=models.CheckConstraint(condition=models.Q(('quantity_delta', 0), _negated=True), name='movement_delta_not_zero'),
        ),
        append_only_trigger("goods_inventorymovement"),
    ]
