# Generated by Django 5.2.17 on 2026-10-01 03:19

import apps.goods.models
import django.contrib.postgres.fields
import django.core.validators
import django.db.models.deletion
from django.db import migrations, models


def untracked_goods_are_services(apps, schema_editor):
    Good = apps.get_model("goods", "Good")
    Good.objects.filter(track_stock=False).update(kind="SERVICE")


class Migration(migrations.Migration):

    dependencies = [
        ('goods', '0001_initial'),
        ('sellers', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='RentalSettings',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('slot_minutes', models.PositiveSmallIntegerField(help_text='Length of one bookable slot; `price` is charged per slot.', validators=[django.core.validators.MinValueValidator(15), django.core.validators.MaxValueValidator(1440)])),
                ('opening_time', models.TimeField()),
                ('closing_time', models.TimeField()),
                ('weekdays', django.contrib.postgres.fields.ArrayField(base_field=models.PositiveSmallIntegerField(validators=[django.core.validators.MaxValueValidator(6)]), default=apps.goods.models._all_weekdays, help_text='Open days: 0 = Monday ... 6 = Sunday.', size=None)),
                ('max_slots_per_booking', models.PositiveSmallIntegerField(default=4, validators=[django.core.validators.MinValueValidator(1)])),
                ('max_days_ahead', models.PositiveSmallIntegerField(default=30, help_text='How many days in advance a slot can be booked.')),
            ],
        ),
        migrations.AddField(
            model_name='good',
            name='kind',
            field=models.CharField(choices=[('PRODUCT', 'Product (tangible, optional stock)'), ('SERVICE', 'Service (intangible, sold at the till)'), ('RENTAL', 'Rental (booked by time slot)')], default='PRODUCT', max_length=10),
        ),
        migrations.RunPython(untracked_goods_are_services, migrations.RunPython.noop),
        migrations.AddConstraint(
            model_name='good',
            constraint=models.CheckConstraint(condition=models.Q(('kind', 'PRODUCT'), ('track_stock', False), _connector='OR'), name='good_only_products_track_stock'),
        ),
        migrations.AddField(
            model_name='rentalsettings',
            name='good',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='rental', to='goods.good'),
        ),
        migrations.AddConstraint(
            model_name='rentalsettings',
            constraint=models.CheckConstraint(condition=models.Q(('closing_time__gt', models.F('opening_time'))), name='rental_closes_after_opening'),
        ),
        migrations.AddConstraint(
            model_name='rentalsettings',
            constraint=models.CheckConstraint(condition=models.Q(('slot_minutes__gte', 15)), name='rental_slot_at_least_15_min'),
        ),
    ]
