# Generated by Django 5.2.17 on 2026-10-01 11:06

import django.core.validators
from django.db import migrations, models


def daily_limit_equals_booking_limit(apps, schema_editor):
    RentalSettings = apps.get_model("goods", "RentalSettings")
    RentalSettings.objects.update(max_slots_per_day=models.F("max_slots_per_booking"))


class Migration(migrations.Migration):

    dependencies = [
        ('goods', '0002_good_kind_and_rental_settings'),
    ]

    operations = [
        migrations.AddField(
            model_name='rentalsettings',
            name='max_slots_per_day',
            field=models.PositiveSmallIntegerField(default=4, help_text='Most slots one developer may book on this rental per day (all bookings).', validators=[django.core.validators.MinValueValidator(1)]),
        ),
        migrations.RunPython(daily_limit_equals_booking_limit, migrations.RunPython.noop),
    ]
