# Generated by Django 5.2.17 on 2026-09-30 15:32

import django.db.models.deletion
import django.utils.timezone
from django.conf import settings
from django.db import migrations, models

from common.db import append_only_trigger


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('developers', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='DeveloperAccount',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('balance', models.DecimalField(decimal_places=2, default=0, max_digits=14)),
                ('status', models.CharField(choices=[('ACTIVE', 'Active'), ('FROZEN', 'Frozen (can receive money, cannot spend)'), ('CLOSED', 'Closed')], default='ACTIVE', max_length=10)),
                ('status_reason', models.CharField(blank=True, max_length=255)),
                ('developer', models.OneToOneField(on_delete=django.db.models.deletion.PROTECT, related_name='account', to='developers.developer')),
            ],
            options={
                'ordering': ['developer__full_name', 'id'],
            },
        ),
        migrations.CreateModel(
            name='AccountTransaction',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('kind', models.CharField(choices=[('DEPOSIT', 'Deposit'), ('PURCHASE', 'Purchase'), ('REFUND', 'Refund'), ('ADJUSTMENT', 'Manual adjustment')], max_length=12)),
                ('amount', models.DecimalField(decimal_places=2, max_digits=14)),
                ('balance_after', models.DecimalField(decimal_places=2, max_digits=14)),
                ('description', models.CharField(blank=True, max_length=255)),
                ('reference', models.CharField(blank=True, help_text='e.g. purchase id.', max_length=100)),
                ('idempotency_key', models.CharField(blank=True, max_length=64)),
                ('created_at', models.DateTimeField(db_index=True, default=django.utils.timezone.now)),
                ('actor', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='+', to=settings.AUTH_USER_MODEL)),
                ('account', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='transactions', to='finance.developeraccount')),
            ],
            options={
                'ordering': ['-created_at', '-id'],
            },
        ),
        migrations.AddConstraint(
            model_name='developeraccount',
            constraint=models.CheckConstraint(condition=models.Q(('balance__gte', 0)), name='account_balance_not_negative'),
        ),
        migrations.AddIndex(
            model_name='accounttransaction',
            index=models.Index(fields=['account', 'created_at'], name='finance_acc_account_ddb99f_idx'),
        ),
        migrations.AddConstraint(
            model_name='accounttransaction',
            constraint=models.CheckConstraint(condition=models.Q(models.Q(('amount__gt', 0), ('kind', 'DEPOSIT')), models.Q(('amount__gt', 0), ('kind', 'REFUND')), models.Q(('amount__lt', 0), ('kind', 'PURCHASE')), models.Q(('kind', 'ADJUSTMENT'), models.Q(('amount', 0), _negated=True)), _connector='OR'), name='transaction_amount_sign_matches_kind'),
        ),
        migrations.AddConstraint(
            model_name='accounttransaction',
            constraint=models.CheckConstraint(condition=models.Q(('balance_after__gte', 0)), name='transaction_balance_not_negative'),
        ),
        migrations.AddConstraint(
            model_name='accounttransaction',
            constraint=models.UniqueConstraint(models.F('idempotency_key'), condition=models.Q(('idempotency_key', ''), _negated=True), name='transaction_idempotency_key_unique'),
        ),
        append_only_trigger("finance_accounttransaction"),
    ]
