# Generated by Django 5.2.17 on 2026-09-30 16:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('finance', '0002_open_accounts_for_existing_developers'),
    ]

    operations = [
        migrations.AddField(
            model_name='developeraccount',
            name='pin_failed_attempts',
            field=models.PositiveSmallIntegerField(default=0),
        ),
        migrations.AddField(
            model_name='developeraccount',
            name='pin_hash',
            field=models.CharField(blank=True, max_length=128),
        ),
        migrations.AddField(
            model_name='developeraccount',
            name='pin_locked_until',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
