# Generated by Django 5.2.17 on 2026-09-30 11:09

import django.core.validators
import django.db.models.deletion
import django.utils.timezone
from django.conf import settings
from django.db import migrations, models

from common.db import append_only_trigger


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('developers', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='RFIDCard',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('uid', models.CharField(max_length=32, unique=True, validators=[django.core.validators.RegexValidator('^[0-9A-F]{4,32}$', 'UID must be 4-32 hexadecimal characters.')])),
                ('label', models.CharField(blank=True, help_text='Number printed on the card.', max_length=50)),
                ('status', models.CharField(choices=[('ACTIVE', 'Active'), ('BLOCKED', 'Blocked'), ('RETIRED', 'Retired')], default='ACTIVE', max_length=10)),
                ('status_reason', models.CharField(blank=True, max_length=255)),
                ('notes', models.TextField(blank=True)),
            ],
            options={
                'verbose_name': 'RFID card',
                'ordering': ['uid'],
            },
        ),
        migrations.CreateModel(
            name='RFIDDevice',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('code', models.CharField(help_text='e.g. READER-001', max_length=50, unique=True)),
                ('name', models.CharField(blank=True, max_length=100)),
                ('location', models.CharField(blank=True, max_length=255)),
                ('purpose', models.CharField(choices=[('ATTENDANCE', 'Attendance')], default='ATTENDANCE', max_length=20)),
                ('is_active', models.BooleanField(default=True)),
                ('api_key_prefix', models.CharField(db_index=True, editable=False, max_length=8)),
                ('api_key_hash', models.CharField(editable=False, max_length=64)),
                ('last_seen_at', models.DateTimeField(blank=True, null=True)),
            ],
            options={
                'verbose_name': 'RFID device',
                'ordering': ['code'],
            },
        ),
        migrations.CreateModel(
            name='RFIDCardAssignment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('assigned_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('unassigned_at', models.DateTimeField(blank=True, null=True)),
                ('end_reason', models.CharField(blank=True, choices=[('RETURNED', 'Returned'), ('REPLACED', 'Replaced'), ('DEVELOPER_LEFT', 'Developer left'), ('DEVELOPER_DELETED', 'Developer record deleted')], max_length=20)),
                ('assigned_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.PROTECT, related_name='+', to=settings.AUTH_USER_MODEL)),
                ('card', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='assignments', to='rfid.rfidcard')),
                ('developer', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='card_assignments', to='developers.developer')),
                ('unassigned_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='+', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'RFID card assignment',
                'ordering': ['-assigned_at', '-id'],
                'constraints': [models.UniqueConstraint(models.F('card'), condition=models.Q(('unassigned_at__isnull', True)), name='rfid_one_owner_per_card'), models.UniqueConstraint(models.F('developer'), condition=models.Q(('unassigned_at__isnull', True)), name='rfid_one_card_per_developer'), models.CheckConstraint(condition=models.Q(('unassigned_at__isnull', True), ('unassigned_at__gte', models.F('assigned_at')), _connector='OR'), name='rfid_assignment_ends_after_start')],
            },
        ),
        migrations.CreateModel(
            name='RFIDEvent',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('client_event_id', models.CharField(blank=True, help_text='Reader-generated id; a retried request with the same id is not stored twice.', max_length=64)),
                ('uid', models.CharField(max_length=32)),
                ('event_time', models.DateTimeField()),
                ('received_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('result', models.CharField(choices=[('ACCEPTED', 'Accepted'), ('DUPLICATE', 'Duplicate (debounced)'), ('UNKNOWN_CARD', 'Unknown card'), ('UNASSIGNED_CARD', 'Card not assigned'), ('BLOCKED_CARD', 'Card blocked'), ('RETIRED_CARD', 'Card retired'), ('INACTIVE_DEVELOPER', 'Developer not active')], max_length=20)),
                ('card', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='events', to='rfid.rfidcard')),
                ('developer', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='rfid_events', to='developers.developer')),
                ('device', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='events', to='rfid.rfiddevice')),
            ],
            options={
                'verbose_name': 'RFID event',
                'ordering': ['-event_time', '-id'],
                'indexes': [models.Index(fields=['card', 'event_time'], name='rfid_rfidev_card_id_fbbe81_idx'), models.Index(fields=['developer', 'event_time'], name='rfid_rfidev_develop_1ba9e5_idx'), models.Index(fields=['result', 'event_time'], name='rfid_rfidev_result_0d5e77_idx')],
                'constraints': [models.UniqueConstraint(models.F('device'), models.F('client_event_id'), condition=models.Q(('client_event_id', ''), _negated=True), name='rfid_event_client_id_unique')],
            },
        ),
        append_only_trigger("rfid_rfidevent"),
    ]
