# Generated by Django 5.2.17 on 2026-09-30 11:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('rfid', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='rfiddevice',
            name='direction',
            field=models.CharField(choices=[('IN', 'Entrance'), ('OUT', 'Exit'), ('BOTH', 'Entrance and exit')], default='BOTH', help_text="Used by the attendance 'device' rule to label scans IN/OUT.", max_length=4),
        ),
    ]
