# Generated by Django 5.2.17 on 2026-10-01 04:25

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('rfid', '0002_rfiddevice_direction'),
        ('sellers', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='rfiddevice',
            name='app_version',
            field=models.CharField(blank=True, help_text='Firmware or program version, from heartbeats.', max_length=50),
        ),
        migrations.AddField(
            model_name='rfiddevice',
            name='last_ip',
            field=models.GenericIPAddressField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='rfiddevice',
            name='service_position',
            field=models.ForeignKey(blank=True, help_text="TILL devices only: the counter whose purchases receive this reader's taps.", null=True, on_delete=django.db.models.deletion.PROTECT, related_name='till_devices', to='sellers.serviceposition'),
        ),
        migrations.AlterField(
            model_name='rfiddevice',
            name='purpose',
            field=models.CharField(choices=[('ATTENDANCE', 'Attendance reader'), ('TILL', "Till card reader (program on a seller's computer)")], default='ATTENDANCE', max_length=20),
        ),
        migrations.AddConstraint(
            model_name='rfiddevice',
            constraint=models.CheckConstraint(condition=models.Q(models.Q(('purpose', 'TILL'), ('service_position__isnull', False)), models.Q(models.Q(('purpose', 'TILL'), _negated=True), ('service_position__isnull', True)), _connector='OR'), name='rfid_till_device_has_position'),
        ),
    ]
