# Generated by Django 5.2.17 on 2026-10-01 05:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('rfid', '0003_rfiddevice_app_version_rfiddevice_last_ip_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='rfidevent',
            name='direction',
            field=models.CharField(blank=True, choices=[('IN', 'In'), ('OUT', 'Out')], help_text='In/out as reported by the device with this scan (blank if not reported).', max_length=3),
        ),
    ]
