# Generated by Django 5.2.17 on 2026-10-01 06:07

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('rfid', '0004_rfidevent_direction'),
        ('sellers', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Building',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('code', models.CharField(help_text='e.g. B1', max_length=20, unique=True)),
                ('name', models.CharField(help_text='e.g. Building 1', max_length=100, unique=True)),
            ],
            options={
                'ordering': ['code'],
            },
        ),
        migrations.AddField(
            model_name='rfiddevice',
            name='building',
            field=models.ForeignKey(blank=True, help_text='ATTENDANCE devices: the building whose door this is (for occupancy).', null=True, on_delete=django.db.models.deletion.PROTECT, related_name='devices', to='rfid.building'),
        ),
        migrations.AddConstraint(
            model_name='rfiddevice',
            constraint=models.CheckConstraint(condition=models.Q(('purpose', 'ATTENDANCE'), ('building__isnull', True), _connector='OR'), name='rfid_only_attendance_devices_have_building'),
        ),
    ]
