# Generated by Django 5.2.17 on 2026-10-01 06:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('rfid', '0005_buildings'),
        ('sellers', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='rfiddevice',
            name='allowed_ip',
            field=models.GenericIPAddressField(blank=True, help_text="ATTENDANCE doors that cannot send an API key: requests from this fixed IP that carry this device's code as `ID` are accepted without a key.", null=True),
        ),
        migrations.AddConstraint(
            model_name='rfiddevice',
            constraint=models.CheckConstraint(condition=models.Q(('purpose', 'ATTENDANCE'), ('allowed_ip__isnull', True), _connector='OR'), name='rfid_only_attendance_devices_use_ip_auth'),
        ),
    ]
