# Generated by Django 5.2.17 on 2026-10-01 07:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('rfid', '0006_device_allowed_ip'),
        ('sellers', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='rfiddevice',
            name='sn_hash',
            field=models.CharField(blank=True, editable=False, help_text="SHA-256 of the till reader's serial number (it authenticates by SN + ID).", max_length=64),
        ),
        migrations.AddField(
            model_name='rfiddevice',
            name='sn_hint',
            field=models.CharField(blank=True, editable=False, help_text='Last 4 characters of the SN.', max_length=4),
        ),
        migrations.AddConstraint(
            model_name='rfiddevice',
            constraint=models.CheckConstraint(condition=models.Q(('purpose', 'TILL'), ('sn_hash', ''), _connector='OR'), name='rfid_only_till_devices_use_sn_auth'),
        ),
    ]
