# Generated by Django 5.2.17 on 2026-10-01 08:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('rfid', '0007_till_serial_number'),
        ('sellers', '0001_initial'),
    ]

    operations = [
        migrations.RemoveConstraint(
            model_name='rfiddevice',
            name='rfid_only_till_devices_use_sn_auth',
        ),
        migrations.RemoveField(
            model_name='rfiddevice',
            name='sn_hash',
        ),
        migrations.RemoveField(
            model_name='rfiddevice',
            name='sn_hint',
        ),
        migrations.AddField(
            model_name='rfiddevice',
            name='sn',
            field=models.CharField(blank=True, help_text='TILL readers: serial number they send as `SN`; with `ID` it authenticates them.', max_length=100),
        ),
        migrations.AddConstraint(
            model_name='rfiddevice',
            constraint=models.CheckConstraint(condition=models.Q(('purpose', 'TILL'), ('sn', ''), _connector='OR'), name='rfid_only_till_devices_have_sn'),
        ),
        migrations.AddConstraint(
            model_name='rfiddevice',
            constraint=models.UniqueConstraint(models.F('sn'), condition=models.Q(('sn', ''), _negated=True), name='rfid_device_sn_unique'),
        ),
    ]
