# Generated by Django 5.2.17 on 2026-10-01 08:36

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('rfid', '0008_till_sn_plain'),
    ]

    operations = [
        migrations.RemoveConstraint(
            model_name='rfiddevice',
            name='rfid_till_device_has_position',
        ),
        migrations.RemoveField(
            model_name='rfiddevice',
            name='service_position',
        ),
    ]
