# Generated by Django 5.2.17 on 2026-10-01 09:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('rfid', '0009_till_reader_not_counter'),
    ]

    operations = [
        migrations.AddField(
            model_name='rfidevent',
            name='source_ip',
            field=models.GenericIPAddressField(blank=True, help_text='Network address the scan came from.', null=True),
        ),
    ]
