# Generated by Django 5.2.17 on 2026-10-01 16:23

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('rfid', '0010_match_reader_by_ip'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='building',
            name='managers',
            field=models.ManyToManyField(blank=True, related_name='managed_buildings', to=settings.AUTH_USER_MODEL),
        ),
    ]
