# Generated by Django 5.2.17 on 2026-10-03 02:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('rfid', '0012_building_owners'),
    ]

    operations = [
        migrations.RemoveConstraint(
            model_name='rfiddevice',
            name='rfid_only_till_devices_have_sn',
        ),
        migrations.AlterField(
            model_name='rfiddevice',
            name='purpose',
            field=models.CharField(choices=[('ATTENDANCE', 'Attendance reader'), ('TILL', "Till card reader (program on a seller's computer)"), ('ENROLL', 'Card assign reader')], default='ATTENDANCE', max_length=20),
        ),
        migrations.AlterField(
            model_name='rfiddevice',
            name='sn',
            field=models.CharField(blank=True, help_text='TILL and card assign readers: serial number they send as `SN`. Tills also send their code as `ID`; card assign readers send `ID` "Master".', max_length=100),
        ),
        migrations.AddConstraint(
            model_name='rfiddevice',
            constraint=models.CheckConstraint(condition=models.Q(('purpose__in', ('TILL', 'ENROLL')), ('sn', ''), _connector='OR'), name='rfid_only_sn_devices_have_sn'),
        ),
    ]
