# Generated by Django 5.2.17 on 2026-10-03 12:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('rfid', '0013_enroll_readers'),
    ]

    operations = [
        migrations.RemoveConstraint(
            model_name='rfiddevice',
            name='rfid_device_sn_unique',
        ),
        migrations.RemoveConstraint(
            model_name='rfiddevice',
            name='rfid_only_sn_devices_have_sn',
        ),
        migrations.RemoveField(
            model_name='rfiddevice',
            name='sn',
        ),
        migrations.AlterField(
            model_name='rfiddevice',
            name='code',
            field=models.CharField(help_text='The ID the device sends, e.g. Door1, Reader1, Master1. Several door units may share one ID; each is then a separate device told apart by its allowed IP.', max_length=50),
        ),
        migrations.AddConstraint(
            model_name='rfiddevice',
            constraint=models.UniqueConstraint(models.F('code'), condition=models.Q(('purpose', 'ATTENDANCE'), _negated=True), name='rfid_device_code_unique'),
        ),
        migrations.AddConstraint(
            model_name='rfiddevice',
            constraint=models.UniqueConstraint(models.F('code'), models.F('allowed_ip'), condition=models.Q(('purpose', 'ATTENDANCE')), name='rfid_door_code_ip_unique', nulls_distinct=False),
        ),
    ]
