# Generated by Django 5.2.17 on 2026-10-03 14:55

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('rfid', '0014_device_ids_without_sn'),
        ('sellers', '0002_position_building_manager'),
    ]

    operations = [
        migrations.AddField(
            model_name='rfiddevice',
            name='seller',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='till_readers', to='sellers.seller'),
        ),
        migrations.AddConstraint(
            model_name='rfiddevice',
            constraint=models.CheckConstraint(condition=models.Q(('purpose', 'TILL'), ('seller__isnull', True), _connector='OR'), name='rfid_only_tills_have_a_seller'),
        ),
    ]
