# Generated by Django 5.2.17 on 2026-10-03 15:43

import django.db.models.deletion
import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('rfid', '0015_till_readers_belong_to_sellers'),
    ]

    operations = [
        migrations.CreateModel(
            name='TCPFrameLog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('received_at', models.DateTimeField(db_index=True, default=django.utils.timezone.now)),
                ('peer_ip', models.GenericIPAddressField(blank=True, null=True)),
                ('request', models.TextField(blank=True, help_text='The packet as received, without the $ marks.')),
                ('device_code', models.CharField(blank=True, help_text='The ID it named.', max_length=50)),
                ('response', models.TextField(blank=True, help_text='Exactly what was sent back.')),
                ('outcome', models.CharField(choices=[('OK', 'Handled'), ('REJECTED', 'Unknown device or address'), ('INVALID', 'Invalid packet'), ('REFUSED', 'Connection refused'), ('ERROR', 'Server error')], max_length=10)),
                ('note', models.CharField(blank=True, help_text='Why it was refused.', max_length=300)),
                ('duration_ms', models.PositiveIntegerField(default=0)),
                ('device', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to='rfid.rfiddevice')),
                ('event', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to='rfid.rfidevent')),
            ],
            options={
                'verbose_name': 'TCP log entry',
                'ordering': ['-received_at', '-id'],
                'indexes': [models.Index(fields=['outcome', 'received_at'], name='rfid_tcpfra_outcome_145baa_idx'), models.Index(fields=['peer_ip', 'received_at'], name='rfid_tcpfra_peer_ip_122442_idx'), models.Index(fields=['device_code', 'received_at'], name='rfid_tcpfra_device__c139bf_idx')],
            },
        ),
    ]
