# Generated by Django 5.2.17 on 2026-09-30 11:00

import django.db.models.deletion
import django.db.models.functions.text
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Developer',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('deleted_at', models.DateTimeField(blank=True, db_index=True, null=True)),
                ('employee_number', models.CharField(max_length=50)),
                ('full_name', models.CharField(max_length=255)),
                ('email', models.EmailField(max_length=254)),
                ('phone', models.CharField(blank=True, max_length=50)),
                ('department', models.CharField(blank=True, db_index=True, max_length=100)),
                ('position_title', models.CharField(blank=True, max_length=100)),
                ('start_date', models.DateField(blank=True, null=True)),
                ('status', models.CharField(choices=[('ACTIVE', 'Active'), ('ON_LEAVE', 'On leave'), ('SUSPENDED', 'Suspended'), ('TERMINATED', 'Terminated')], default='ACTIVE', max_length=20)),
                ('manager', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='reports', to='developers.developer')),
                ('user', models.ForeignKey(blank=True, help_text='Login account; optional until the developer needs self-service access.', null=True, on_delete=django.db.models.deletion.PROTECT, related_name='developer_profiles', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['full_name', 'id'],
                'indexes': [models.Index(fields=['status', 'department'], name='developers__status_30d873_idx')],
                'constraints': [models.UniqueConstraint(models.F('employee_number'), condition=models.Q(('deleted_at__isnull', True)), name='developer_employee_number_unique'), models.UniqueConstraint(django.db.models.functions.text.Lower('email'), condition=models.Q(('deleted_at__isnull', True)), name='developer_email_ci_unique'), models.UniqueConstraint(models.F('user'), condition=models.Q(('deleted_at__isnull', True)), name='developer_user_unique'), models.CheckConstraint(condition=models.Q(('manager', models.F('id')), _negated=True), name='developer_not_own_manager')],
            },
        ),
    ]
