# Generated by Django 5.2.17 on 2026-10-01 02:34

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('developers', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.RemoveConstraint(
            model_name='developer',
            name='developer_email_ci_unique',
        ),
        migrations.RemoveField(
            model_name='developer',
            name='email',
        ),
        migrations.AddField(
            model_name='developer',
            name='birthday',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='developer',
            name='home_address',
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name='developer',
            name='out_date',
            field=models.DateField(blank=True, help_text='Last working day (set when the developer leaves).', null=True),
        ),
        migrations.AddConstraint(
            model_name='developer',
            constraint=models.CheckConstraint(condition=models.Q(('out_date__isnull', True), ('start_date__isnull', True), ('out_date__gte', models.F('start_date')), _connector='OR'), name='developer_out_date_after_start'),
        ),
    ]
