# Generated by Django 5.2.17 on 2026-10-01 16:23

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('developers', '0002_email_removed_address_birthday_out_date'),
        ('rfid', '0011_building_managers'),
    ]

    operations = [
        migrations.AddField(
            model_name='developer',
            name='building',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='developers', to='rfid.building'),
        ),
    ]
