# Generated by Django 5.2.17 on 2026-10-03 03:33

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('developers', '0003_building_managers'),
    ]

    operations = [
        migrations.RemoveConstraint(
            model_name='developer',
            name='developer_not_own_manager',
        ),
        migrations.RemoveField(
            model_name='developer',
            name='manager',
        ),
    ]
