# Generated by Django 5.2.17 on 2026-09-30 11:31

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('developers', '0001_initial'),
        ('rfid', '0002_rfiddevice_direction'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='AttendanceRecord',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('work_date', models.DateField(help_text='Company-local working day this record counts for.')),
                ('event_time', models.DateTimeField()),
                ('event_type', models.CharField(choices=[('IN', 'In'), ('OUT', 'Out'), ('SCAN', 'Scan (direction not classified)')], default='SCAN', max_length=4)),
                ('source', models.CharField(choices=[('RFID', 'RFID scan'), ('MANUAL', 'Manual correction')], max_length=6)),
                ('note', models.CharField(blank=True, max_length=255)),
                ('is_void', models.BooleanField(default=False)),
                ('void_reason', models.CharField(blank=True, max_length=255)),
                ('voided_at', models.DateTimeField(blank=True, null=True)),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='+', to=settings.AUTH_USER_MODEL)),
                ('developer', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='attendance_records', to='developers.developer')),
                ('device', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='+', to='rfid.rfiddevice')),
                ('rfid_event', models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='attendance_record', to='rfid.rfidevent')),
                ('voided_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='+', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['event_time', 'id'],
                'indexes': [models.Index(fields=['developer', 'work_date'], name='attendance__develop_4b6ce5_idx')],
                'constraints': [models.CheckConstraint(condition=models.Q(('source', 'MANUAL'), ('rfid_event__isnull', False), _connector='OR'), name='attendance_rfid_record_has_event'), models.CheckConstraint(condition=models.Q(('source', 'RFID'), models.Q(('note', ''), _negated=True), _connector='OR'), name='attendance_manual_record_has_note'), models.CheckConstraint(condition=models.Q(('is_void', False), models.Q(('void_reason', ''), _negated=True), _connector='OR'), name='attendance_void_has_reason')],
            },
        ),
        migrations.CreateModel(
            name='DailyAttendance',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('work_date', models.DateField()),
                ('first_seen', models.DateTimeField()),
                ('last_seen', models.DateTimeField(blank=True, null=True)),
                ('record_count', models.PositiveIntegerField()),
                ('worked_seconds', models.PositiveIntegerField()),
                ('status', models.CharField(choices=[('PRESENT', 'Present'), ('INCOMPLETE', 'Incomplete (missing or unpaired scan)')], max_length=10)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('developer', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='daily_attendance', to='developers.developer')),
            ],
            options={
                'verbose_name_plural': 'daily attendance',
                'ordering': ['-work_date', 'developer_id'],
                'indexes': [models.Index(fields=['work_date', 'status'], name='attendance__work_da_db18b0_idx')],
                'constraints': [models.UniqueConstraint(fields=('developer', 'work_date'), name='attendance_one_summary_per_day')],
            },
        ),
    ]
