# Generated by Django 5.2.17 on 2026-10-01 06:10

from django.conf import settings
from django.db import migrations, models


def copy_scan_directions(apps, schema_editor):
    AttendanceRecord = apps.get_model("attendance", "AttendanceRecord")
    RFIDEvent = apps.get_model("rfid", "RFIDEvent")
    AttendanceRecord.objects.filter(rfid_event__isnull=False).update(
        direction=models.Subquery(
            RFIDEvent.objects.filter(pk=models.OuterRef("rfid_event_id")).values("direction")[:1]
        )
    )


class Migration(migrations.Migration):

    dependencies = [
        ("rfid", "0005_buildings"),
        ('attendance', '0001_initial'),
        ('developers', '0002_email_removed_address_birthday_out_date'),
        ('rfid', '0005_buildings'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='attendancerecord',
            name='direction',
            field=models.CharField(blank=True, choices=[('IN', 'In'), ('OUT', 'Out')], help_text='In/out as reported by the door, or as entered on a manual correction.', max_length=3),
        ),
        migrations.RunPython(copy_scan_directions, migrations.RunPython.noop),
        migrations.AddIndex(
            model_name='attendancerecord',
            index=models.Index(fields=['developer', '-event_time', '-id'], name='attendance_latest_idx'),
        ),
    ]
