# Generated by Django 5.2.17 on 2026-10-01 06:15

import django.db.models.deletion
from django.db import migrations, models


def fill_presence(apps, schema_editor):
    AttendanceRecord = apps.get_model("attendance", "AttendanceRecord")
    DeveloperPresence = apps.get_model("attendance", "DeveloperPresence")
    for developer_id in AttendanceRecord.objects.values_list("developer_id", flat=True).distinct():
        latest = (
            AttendanceRecord.objects.select_related("device")
            .filter(developer_id=developer_id, is_void=False)
            .order_by("-event_time", "-id")
            .first()
        )
        inside = latest is not None and latest.event_type == "IN"
        DeveloperPresence.objects.update_or_create(
            developer_id=developer_id,
            defaults={
                "is_inside": inside,
                "building_id": latest.device.building_id if inside and latest.device else None,
                "since": latest.event_time if latest else None,
                "record": latest,
            },
        )


class Migration(migrations.Migration):

    dependencies = [
        ('attendance', '0002_record_direction'),
        ('developers', '0002_email_removed_address_birthday_out_date'),
        ('rfid', '0005_buildings'),
    ]

    operations = [
        migrations.CreateModel(
            name='DeveloperPresence',
            fields=[
                ('developer', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, primary_key=True, related_name='presence', serialize=False, to='developers.developer')),
                ('is_inside', models.BooleanField(default=False)),
                ('since', models.DateTimeField(blank=True, help_text='Time of the latest record.', null=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('building', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to='rfid.building')),
                ('record', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to='attendance.attendancerecord')),
            ],
            options={
                'indexes': [models.Index(fields=['is_inside', 'building'], name='attendance__is_insi_39c115_idx')],
            },
        ),
        migrations.RunPython(fill_presence, migrations.RunPython.noop),
    ]
