# Generated by Django 5.2.17 on 2026-10-01 03:22

import apps.bookings.models
import django.contrib.postgres.constraints
import django.contrib.postgres.fields.ranges
import django.db.models.deletion
from django.contrib.postgres.operations import BtreeGistExtension
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('developers', '0002_email_removed_address_birthday_out_date'),
        ('goods', '0002_good_kind_and_rental_settings'),
        ('purchases', '0001_initial'),
    ]

    operations = [
        # Needed by the booking_no_overlap exclusion constraint (good = AND range &&).
        BtreeGistExtension(),
        migrations.CreateModel(
            name='Booking',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('start', models.DateTimeField()),
                ('end', models.DateTimeField()),
                ('slots', models.PositiveSmallIntegerField()),
                ('developer', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='bookings', to='developers.developer')),
                ('good', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='bookings', to='goods.good')),
                ('purchase', models.OneToOneField(on_delete=django.db.models.deletion.PROTECT, related_name='booking', to='purchases.purchase')),
            ],
            options={
                'ordering': ['-start', '-id'],
                'indexes': [models.Index(fields=['developer', 'start'], name='bookings_bo_develop_2b4a05_idx')],
                'constraints': [models.CheckConstraint(condition=models.Q(('end__gt', models.F('start'))), name='booking_ends_after_start'), django.contrib.postgres.constraints.ExclusionConstraint(expressions=[('good', '='), (apps.bookings.models.TsTzRange('start', 'end', django.contrib.postgres.fields.ranges.RangeBoundary()), '&&')], name='booking_no_overlap')],
            },
        ),
    ]
