# Generated by Django 5.2.17 on 2026-10-01 11:15

import apps.bookings.models
import django.contrib.postgres.constraints
import django.contrib.postgres.fields.ranges
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('bookings', '0001_initial'),
        ('developers', '0002_email_removed_address_birthday_out_date'),
        ('goods', '0003_rental_daily_limit'),
        ('purchases', '0004_match_reader_by_ip'),
    ]

    operations = [
        migrations.AddConstraint(
            model_name='booking',
            constraint=django.contrib.postgres.constraints.ExclusionConstraint(expressions=[('developer', '='), (apps.bookings.models.TsTzRange('start', 'end', django.contrib.postgres.fields.ranges.RangeBoundary()), '&&')], name='booking_one_court_per_developer'),
        ),
    ]
