# Generated by Django 5.2.17 on 2026-10-01 15:10

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bookings', '0002_one_court_per_developer'),
        ('purchases', '0005_booking_at_desk'),
    ]

    operations = [
        migrations.AlterField(
            model_name='booking',
            name='purchase',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='bookings', to='purchases.purchase'),
        ),
    ]
