# Generated by Django 5.2.17 on 2026-09-30 16:04

import django.core.validators
import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('developers', '0001_initial'),
        ('finance', '0003_developeraccount_pin_failed_attempts_and_more'),
        ('goods', '0001_initial'),
        ('rfid', '0002_rfiddevice_direction'),
        ('sellers', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Purchase',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('status', models.CharField(choices=[('DRAFT', 'Draft (bucket being built)'), ('CONFIRMED', 'Confirmed (paid)'), ('CANCELLED', 'Cancelled')], default='DRAFT', max_length=10)),
                ('total', models.DecimalField(blank=True, decimal_places=2, max_digits=14, null=True)),
                ('confirm_idempotency_key', models.CharField(blank=True, max_length=64)),
                ('confirmed_at', models.DateTimeField(blank=True, null=True)),
                ('cancelled_at', models.DateTimeField(blank=True, null=True)),
                ('account_transaction', models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='+', to='finance.accounttransaction')),
                ('card', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='purchases', to='rfid.rfidcard')),
                ('confirmed_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='+', to=settings.AUTH_USER_MODEL)),
                ('created_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.PROTECT, related_name='+', to=settings.AUTH_USER_MODEL)),
                ('developer', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='purchases', to='developers.developer')),
                ('seller', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='purchases', to='sellers.seller')),
                ('service_position', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='purchases', to='sellers.serviceposition')),
            ],
            options={
                'ordering': ['-created_at', '-id'],
            },
        ),
        migrations.CreateModel(
            name='PurchaseItem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('quantity', models.PositiveIntegerField(validators=[django.core.validators.MinValueValidator(1), django.core.validators.MaxValueValidator(999)])),
                ('unit_price', models.DecimalField(blank=True, decimal_places=2, max_digits=14, null=True)),
                ('line_total', models.DecimalField(blank=True, decimal_places=2, max_digits=14, null=True)),
                ('good', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='purchase_items', to='goods.good')),
                ('purchase', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='items', to='purchases.purchase')),
            ],
            options={
                'ordering': ['id'],
            },
        ),
        migrations.AddIndex(
            model_name='purchase',
            index=models.Index(fields=['seller', 'status', 'created_at'], name='purchases_p_seller__f7e939_idx'),
        ),
        migrations.AddIndex(
            model_name='purchase',
            index=models.Index(fields=['developer', 'confirmed_at'], name='purchases_p_develop_51f51b_idx'),
        ),
        migrations.AddConstraint(
            model_name='purchase',
            constraint=models.UniqueConstraint(models.F('confirm_idempotency_key'), condition=models.Q(('confirm_idempotency_key', ''), _negated=True), name='purchase_confirm_key_unique'),
        ),
        migrations.AddConstraint(
            model_name='purchase',
            constraint=models.CheckConstraint(condition=models.Q(models.Q(('status', 'CONFIRMED'), _negated=True), models.Q(('account_transaction__isnull', False), ('confirmed_at__isnull', False), ('developer__isnull', False), ('total__isnull', False)), _connector='OR'), name='purchase_confirmed_is_complete'),
        ),
        migrations.AddConstraint(
            model_name='purchaseitem',
            constraint=models.UniqueConstraint(fields=('purchase', 'good'), name='purchase_item_good_unique'),
        ),
        migrations.AddConstraint(
            model_name='purchaseitem',
            constraint=models.CheckConstraint(condition=models.Q(('quantity__gte', 1)), name='purchase_item_quantity_min'),
        ),
    ]
