# Generated by Django 5.2.17 on 2026-10-01 04:25

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('purchases', '0001_initial'),
        ('rfid', '0002_rfiddevice_direction'),
    ]

    operations = [
        migrations.AddField(
            model_name='purchase',
            name='presented_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='purchase',
            name='presented_event',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='+', to='rfid.rfidevent'),
        ),
    ]
