# Generated by Django 5.2.17 on 2026-10-01 08:36

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('developers', '0002_email_removed_address_birthday_out_date'),
        ('finance', '0003_developeraccount_pin_failed_attempts_and_more'),
        ('purchases', '0002_purchase_presented_at_purchase_presented_event'),
        ('rfid', '0009_till_reader_not_counter'),
        ('sellers', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='purchase',
            name='reader',
            field=models.ForeignKey(blank=True, limit_choices_to={'purpose': 'TILL'}, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='purchases', to='rfid.rfiddevice'),
        ),
        migrations.AddIndex(
            model_name='purchase',
            index=models.Index(fields=['reader', 'status', 'created_at'], name='purchases_p_reader__0aa669_idx'),
        ),
    ]
