# Generated by Django 5.2.17 on 2026-10-01 09:37

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('developers', '0002_email_removed_address_birthday_out_date'),
        ('finance', '0003_developeraccount_pin_failed_attempts_and_more'),
        ('purchases', '0003_till_reader_not_counter'),
        ('rfid', '0010_match_reader_by_ip'),
        ('sellers', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='purchase',
            name='client_ip',
            field=models.GenericIPAddressField(blank=True, null=True),
        ),
        migrations.AddIndex(
            model_name='purchase',
            index=models.Index(fields=['client_ip', 'status', 'created_at'], name='purchases_p_client__214437_idx'),
        ),
    ]
