# Generated by Django 5.2.17 on 2026-10-01 15:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('purchases', '0004_match_reader_by_ip'),
    ]

    operations = [
        migrations.AddField(
            model_name='purchaseitem',
            name='start',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
