# Generated by Django 5.2.17 on 2026-10-01 16:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('purchases', '0005_booking_at_desk'),
    ]

    operations = [
        migrations.AddField(
            model_name='purchase',
            name='kind',
            field=models.CharField(choices=[('SALE', 'Sale of goods at a till'), ('BOOKING', 'Court booking checkout')], default='SALE', max_length=10),
        ),
    ]
