# Generated by Django 5.2.17 on 2026-10-03 14:55

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('developers', '0004_remove_developer_manager'),
        ('finance', '0003_developeraccount_pin_failed_attempts_and_more'),
        ('purchases', '0006_split_bookings'),
        ('rfid', '0014_device_ids_without_sn'),
        ('sellers', '0002_position_building_manager'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.RemoveIndex(
            model_name='purchase',
            name='purchases_p_client__214437_idx',
        ),
        migrations.AddField(
            model_name='purchase',
            name='waiting_since',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddIndex(
            model_name='purchase',
            index=models.Index(fields=['reader', 'status', 'waiting_since'], name='purchases_p_reader__c7d6f4_idx'),
        ),
    ]
